name: 'CreatePrComment'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "CreatePrComment/**"
  workflow_dispatch:

env:
  WORKDIR: "CreatePrComment"

defaults:
  run:
    working-directory: "CreatePrComment"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version: [10, 14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: "Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}"
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: "${{ env.WORKDIR }}/package-lock.json"
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test --if-present
    - run: npm run report --if-present
